[package]
name = "ros_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = { version = "0.9.6", features = ["luajit"] }
rand = "0.8.5"
regex = "1.10.3"
